server:
  port: 9098

spring:
  application:
    name: spring-consul-client-student-service
  cloud:
    consul:
      host: consul.local
      port: 8500
      discovery:
        prefer-ip-address: true
#        service-name: spring-consul-client-school-service
#      discovery:
#        instance-id: consul-client-school-service-container
